# data paths
storage_data_raw : /data/raw
storage_data_import : /data/import

storage_runname:
    delimiter: '_'
    field_ID: 1
    field_flowcell: 2
    filed_kit: 3

# threading
threads_basecalling: 4
threads_alignment: 3
threads_methylation: 4
threads_sv: 4
threads_demux: 4

# basecalling
basecalling_albacore_barcoding: false
basecalling_albacore_disable_filtering: true

# alignment
alignment_default_basecaller: flappie
alignment_minimap2_flags: '-ax map-ont -L'
alignment_graphmap_flags: '-B 100'
alignment_ngmlr_flags: '-x ont --bam-fix'

# methylation detection
methylation_nanopolish_logp_threshold: 2.5
methylation_nanopolish_aligner: miniap2
methylation_min_coverage: 1

# demux
deepbinner_models:
    default: SQK-RBK004_read_starts
    EXP-NBD103: EXP-NBD103_read_starts
    SQK-RBK004: SQK-RBK004_read_starts
