# data paths
data_raw : /data/raw
data_import : /data/import
runname:
    delimiter: '_'
    field_ID: 1
    field_flowcell: 2
    filed_kit: 3


# basecalling
albacore_barcoding: false
albacore_disable_filtering: true

# methylation detection
methylation_min_coverage: 1
