jobs: 8

## Uncomment to use threads/CPUs as consumable resources
# resources: threads=8

shadow-prefix: /tmp/nanopype_snakemake
latency-wait: 60
restart-times: 1
cluster: slurm-submit.py
cluster-status: slurm-status.py
jobscript: slurm-jobscript.sh
